version: "3.10"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000

  streamlit:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - 8501:8501
