version: '3.10'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - 5001:5000

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501