name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag age-detection-image

    - name: Run tests
      run: docker run age-detection-image python -m pytest tests/