name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build the FastAPI Docker image
      run: docker build . --file Dockerfile.fastapi --tag age-detection-api-image

    - name: Build the streamlit Docker image
      run: docker build . --file Dockerfile.streamlit --tag age-detection-ui-image

    - name: Run tests
      run: docker run age-detection-api-image python -m pytest tests/